### ISSUE TITLE
建立测试集

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_ai#1]
1.建立分类，检测，分割的基础测试集和标准测试集，要求日常测试集不得超过5万张。（基础测试集定义为日常训练模型和修正模型使用，标准测试集为训练好的backbone和定义最终的精度指标）
2.建立测试集的基础精度作为后续的训练基线
3.记录所有的精度测试并绘制成表格存档

**Comment by foww-0001** [comment]
### 分类数据集
|  数据名称   | 数据总量  |  数据类别  |
|  ----  | ----  |  ----  |
| caltech257_classify  | 30607 | 257 |

**Comment by MiniBullLab** [comment]
### 检测数据集基础测试集
|  数据名称   | 数据总量  |  数据类别  |  图像大小  |  数据集描述  |
|  ----  | ----  |  ----  |  ----  |  ----  |
| object365_detection  | 30351 | 111 |  大小不统一  |  网上的图片爬取，包含了111种日常常见的物品，包括人，车，杯子等等  |

### 检测基础测试集baseline
|  数据名称   | 模型名称  |  训练输入  |  训练学习率  |  训练迭代次数  |  训练时长  |  训练精度  |
|  ----  | ----  |  ----  |  ----  |  ----  |  ----  |  ----  |
| object365_detection  | darknet53_yolov3  |  416×416 | 0.000002~0.0002 multi-step  |  100  |  36h   |  15.1  |

**Comment by MiniBullLab** [comment]
### 缺陷数据集基础测试集
|  数据名称   | 数据总量  |  数据类别  |  图像大小  |  数据集描述  |
|  ----  | ----  |  ----  |  ----  |  ----  |
| magneticshoe_defect_segment  | 238 | 4 |  大小不统一  |  瓷瓦的缺陷，包括洞，划痕缺陷等等  |

### 缺陷基础测试集baseline
|  数据名称   | 模型名称  |  训练输入  |  训练学习率  |  训练迭代次数  |  训练时长  |  训练精度  |
|  ----  | ----  |  ----  |  ----  |  ----  |  ----  |  ----  |
| object365_detection  | darknet53_yolov3  |  416×416 | 0.000002~0.0002 multi-step  |  100  |  36h   |  15.1  |
