### ISSUE TITLE
压缩，量化，半精度训练

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_ai#23]
1.Apex训练环境搭建
2.Apex半精度训练
3.模型稀疏化训练
4.模型压缩
5.模型量化

**Comment by lpj0822** [comment]
* 先安装官方编译好的pytorch库
* 使得torch.version.cuda版本与机器安装的cuda版本匹配
* 然后安装apex，https://github.com/NVIDIA/apex

**Comment by lpj0822** [comment]
Apex半精度训练代码已经添加

**Comment by MiniBullLab** [comment]
量化可以参考pytorch中的量化[https://mp.weixin.qq.com/s?__biz=MzIwMTc4ODE0Mw==&mid=2247519838&idx=2&sn=afb9732ee518119363abff6f06950451&chksm=96ea51dea19dd8c871e2abfa0376998e2ca86e42e42762a6dd7df8f7b860d17da6e239a9b6ab&mpshare=1&scene=1&srcid=0202IO28SPjwvRLT8LWUxovf&sharer_sharetime=1612246306431&sharer_shareid=0c4f297be89f17f4c66af263ef81a90a&exportkey=Ab9hw2ONgSC%2BewmlghjF0ak%3D&pass_ticket=zp2gZ7n2w4IZLfr9JrrSPTK8s9uoL97EOR16yukdCvNj%2BAq3vR4DSauwfkW4uksy&wx_header=0#rd](url)
