### ISSUE TITLE
训练中train和val分配个数错误

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#31]
1. 训练打包好的库中的SegNET时，图片总共27张，train分配了2张，val分配了25张。
2. 训练打包好的库中的ClassNET时，图片总共2000张，train分配了1800张，val分配了200张。
3. 训练打包好的库中的DeNET时，图片总共204张，train分配了184张，val分配了20张。
@lpj0822

**Comment by lpj0822** [comment]
segment任务生成trian.txt与val.txt写反了
