### ISSUE TITLE
segnet网络参数调整

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_ai#47]
1.resize方式
2.normalize方式
3.输入图像大小

**Comment by lpj0822** [comment]
resize方式：0-直接resize
                    1-加pad后按长宽比resize

**Comment by foww-0001** [comment]
Model | resize_type | mIoU(Err)  | GOPS # (G)  | Interpolation | Image Size
| ------ | ------ | ------ | ------ | ------ | ------ |
| segnet | 0 | 73.00(0.0076331) | 30.658 | nearest | 500x400|
| segnet | 1 | 74.21(0.0062603) | 30.658 | nearest | 500x400 |

**Comment by foww-0001** [comment]
Model | resize_type | mIoU(Err)  | GOPS # (G)  | Interpolation | Image Size
| ------ | ------ | ------ | ------ | ------ | ------ |
| segnet | 1 | 74.21(0.0062603) | 30.658 | nearest | 500x400|
| segnet | 1 | 73.20() | 30.658 | nearest | 512x416|
| segnet | 1 | 73.68() | 30.658 | nearest | 544x416 |
| segnet | 1 | 74.48() | 30.658 | nearest | 512x448 |
| segnet | 1 | 74.21() | 30.658 | nearest | 544x448 |
| segnet | 1 | 74.36() | 30.658 | nearest | 512x480 |
| segnet | 1 | 75.29() | 30.658 | nearest | 544x480 |
| segnet | 1 | 74.02() | 30.658 | nearest | 512x512 |
| segnet | 1 | 74.81() | 30.658 | nearest | 544x512 |

**Comment by lpj0822** [comment]
代码已经修改
