### ISSUE TITLE
DeNet测试

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_ai#49]
- [x] 1.Denet运行没有问题

**Comment by foww-0001** [comment]
coord，计算框的权重也有一定的出入。
self.coord_xy_weight = 2.0 * coord_weight
self.coord_wh_weight = 3.0 * coord_weight

conf_neg损失计算有问题，原来的conf_neg误差为1000左右，而现在的conf_neg误差在1左右。

发现tcls同一张图上的真值也不同。

**Comment by foww-0001** [comment]
目前比对出来有五处不同：
1. anchor size:
```
self.anchor_sizes = "8.95,8.57|12.43,26.71|19.71,14.43|" \
                    "26.36,58.52|36.09,25.55|64.42,42.90|" \
                    "96.44,79.10|158.37,115.59|218.65,192.90"
```
2. loss_config中的coord_weight
```
"coord_weight": 1.0,
```
3. coord的权重取值：
```
self.coord_xy_weight = 2.0 * coord_weight
self.coord_wh_weight = 3.0 * coord_weight
```
4. loss使用加和的结果，而非平均的结果：        
```
self.bce_loss = nn.BCELoss(reduction='sum')
self.ce_loss = nn.CrossEntropyLoss(reduction='sum')
```
5. coord_loss也采取加和的结果，不除以 mask_count：
```
loss_coord_wh = (coord_mask * wh_l1_loss).sum() # / mask_count
```
目标只是发现和之前存在的出入，具体的参数配置还要多次测试才能确定，比如anchors。

**Comment by lpj0822** [comment]
anchor原先修改过一次

**Comment by foww-0001** [comment]
### 1.对anchor size进行消融实验，发现修改前后精度变化不大，因此可以考虑不修改anchors。

**Comment by foww-0001** [comment]
### 2,3权重的大小建议先进行保留，等后续大量测试后再进行调整。

**Comment by foww-0001** [comment]
目前除了anchors不需要修改之外，其他的包括权重和loss的选择都按照上面的结果先进行修改。
@lpj0822
